name: Conventional Commit Checks
description: Lint commits for current branch in a comment
author: Devolutions Infrastructure Team

inputs:
  repo-name:
    description: "The name of the repository. Example: 'octocat/hello-world'"
    default: ${{ github.repository }}
  pr-number:
    description: The ID of the pull request (/ issue)
    default: ${{ github.event.number }}
  branch:
    description: Name of the branch
    default: ${{ github.event.pull_request.head.ref }}
  token:
    description: GitHub token
    default: ${{ github.token }}

runs:
  using: composite

  steps:
    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/.cargo/bin/convco
        key: binary-convco

    - name: Install convco
      shell: pwsh
      run: |
        if (-Not (Test-Path -Path ~/.cargo/bin/convco -PathType Leaf)) {
          # Installed in debug because it's faster to compile and we don't need execution speed anyway
          cargo +stable install --debug --locked convco
        }

    - name: Conventional Commits Linter
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      shell: pwsh
      run: ${{ github.action_path }}/bot.ps1 -RepoName ${{ inputs.repo-name }} -PullRequestId ${{ inputs.pr-number }} -Branch ${{ inputs.branch }}

