name: PR Greetings

on:
  pull_request:
    branches: [ main ]
    types: [ opened ]

jobs:
  greetings:
    name: Greetings
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pr-greetings
