name: Release please

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      dryRun:
        default: false
        type: boolean

jobs:
  release-please:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

      - name: Install release-please
        run: npm install --global release-please@13.14.0
      
      - name: Run release-pr
        shell: pwsh
        run: |
          $Args = @('--debug')
          $Args += @('release-pr')
          $Args += @('--token', '${{ github.token }}')
          $Args += @('--repo-url', 'CBenoit/actions-tests')

          if (-Not [string]::IsNullOrWhiteSpace("${{ github.event.inputs.dryRun }}"))
          {
            Write-Host "Executing a dry run"
            $Args += @('--dry-run')
          }

          $Cmd = $(@('release-please') + $Args) -Join ' '
          Write-Host $Cmd

          Invoke-Expression $Cmd

      - name: Run github-release
        shell: pwsh
        run: |
          $Args = @('--debug')
          $Args += @('github-release')
          $Args += @('--token', '${{ github.token }}')
          $Args += @('--repo-url', 'CBenoit/actions-tests')

          if (-Not [string]::IsNullOrWhiteSpace("${{ github.event.inputs.dryRun }}"))
          {
            Write-Host "Executing a dry run"
            $Args += @('--dry-run')
          }

          $Cmd = $(@('release-please') + $Args) -Join ' '
          Write-Host $Cmd

          Invoke-Expression $Cmd

