name: Release crates

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main

jobs:
  # Create a PR with the new versions and changelog, preparing the next release.
  open-pr:
    name: Release-plz PR
    runs-on: ubuntu-latest

    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 512

      - name: Run release-plz
        id: release-plz
        uses: ./.github/actions/release-plz
        with:
          command: release-pr

      - run: |
          echo "pr: ${{ steps.release-plz.outputs.pr }}"
          echo "did-open-pr: ${{ steps.release-plz.outputs.did-open-pr }}"

  # Release unpublished packages.
  release-plz-release:
    name: Release-plz release
    runs-on: ubuntu-latest
    environment: cratesio-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 512

      - name: Run release-plz
        id: release-plz
        uses: ./.github/actions/release-plz
        with:
          command: release
          registry-token: ${{ secrets.CRATES_IO_DEVOLUTIONSBOT_API_KEY }}

      - run: echo "did-publish: ${{ steps.release-plz.outputs.did-publish }}"
